// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqkMorFKKelfPfrBMIpVsAzEfK3EN2Z14',
    appId: '1:550521571100:web:6d1add810c8946a8b0dcd9',
    messagingSenderId: '550521571100',
    projectId: 'tryee-ed2d1',
    authDomain: 'tryee-ed2d1.firebaseapp.com',
    storageBucket: 'tryee-ed2d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI_yVJ8wOS3JLPh4hWu4sg4f9qFpdI1lQ',
    appId: '1:550521571100:android:ead093e8fd91264bb0dcd9',
    messagingSenderId: '550521571100',
    projectId: 'tryee-ed2d1',
    storageBucket: 'tryee-ed2d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzVdP3E4usFMb4YaZedp5zdWrfaWEX9Mo',
    appId: '1:550521571100:ios:702442ba4a9a5787b0dcd9',
    messagingSenderId: '550521571100',
    projectId: 'tryee-ed2d1',
    storageBucket: 'tryee-ed2d1.appspot.com',
    iosBundleId: 'com.example.appchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzVdP3E4usFMb4YaZedp5zdWrfaWEX9Mo',
    appId: '1:550521571100:ios:068f6dcce355d34ab0dcd9',
    messagingSenderId: '550521571100',
    projectId: 'tryee-ed2d1',
    storageBucket: 'tryee-ed2d1.appspot.com',
    iosBundleId: 'com.example.appchat.RunnerTests',
  );
}
